<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterPerbekalanSeeder extends Seeder
{
    /**
     * Seed master perbekalan from dataset in database/seeders/data/perbekalan.xlsx.
     */
    public function run(): void
    {
        $now = now();

        $rows = [
            ['nama_barang' => 'Antangin', 'satuan' => 'Kotak'],
            ['nama_barang' => 'Prima 600 ml', 'satuan' => 'Ctn'],
            ['nama_barang' => 'Aqua Galon', 'satuan' => 'Galon'],
            ['nama_barang' => 'Beras', 'satuan' => 'Karung'],
            ['nama_barang' => 'Betadine', 'satuan' => 'Botol'],
            ['nama_barang' => 'Bodrex', 'satuan' => 'Pack'],
            ['nama_barang' => 'Cup Gelas', 'satuan' => 'Pack'],
            ['nama_barang' => 'Diatabs/Diapet', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Fresh Care', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Garam Balok', 'satuan' => 'Pack'],
            ['nama_barang' => 'Garam Revina', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Gas', 'satuan' => 'Tabung'],
            ['nama_barang' => 'Geliga', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Gula Jawa', 'satuan' => 'Kg'],
            ['nama_barang' => 'Gula Pasir', 'satuan' => 'Kg'],
            ['nama_barang' => 'Hansaplast roll', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Insto', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Kasa', 'satuan' => 'Pack'],
            ['nama_barang' => 'Kecap', 'satuan' => 'Dirijen'],
            ['nama_barang' => 'Kertas Minyak', 'satuan' => 'Pack'],
            ['nama_barang' => 'Kerupuk', 'satuan' => 'kg'],
            ['nama_barang' => 'Komik', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Kopi Kapal Api', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Korek Bara', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Micin', 'satuan' => '250 gr'],
            ['nama_barang' => 'Mie Goreng', 'satuan' => 'Ctn'],
            ['nama_barang' => 'Mie Kuah', 'satuan' => 'Ctn'],
            ['nama_barang' => 'Minyak Cap Kapak', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Minyak Goreng', 'satuan' => '800 ml'],
            ['nama_barang' => 'Minyak Kayu Putih', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Mixagrip', 'satuan' => 'Pleg'],
            ['nama_barang' => 'Paramex', 'satuan' => 'Pleg'],
            ['nama_barang' => 'Pemes / Cutter', 'satuan' => 'Renteng'],
            ['nama_barang' => 'Ponstan', 'satuan' => 'Pleg'],
            ['nama_barang' => 'Revanol / Antiseptik', 'satuan' => 'Pcs'],
            ['nama_barang' => 'Rinso 770 gr', 'satuan' => 'Bungkus'],
            ['nama_barang' => 'Rokok Sampoerna mild', 'satuan' => 'Slop'],
            ['nama_barang' => 'Rokok Signature', 'satuan' => 'Slop'],
            ['nama_barang' => 'Rokok Surya', 'satuan' => 'Slop'],
            ['nama_barang' => 'Royco', 'satuan' => 'Renteng'],
            ['nama_barang' => 'Sabun Colek', 'satuan' => 'Ember'],
            ['nama_barang' => 'Sarung Tangan Kain', 'satuan' => 'Pack'],
            ['nama_barang' => 'Saus ABC', 'satuan' => 'Botol'],
            ['nama_barang' => 'Sprite Kecil', 'satuan' => 'Krat'],
            ['nama_barang' => 'Sunlight', 'satuan' => 'Pouch'],
            ['nama_barang' => 'Susu Coklat', 'satuan' => 'Kaleng'],
            ['nama_barang' => 'Susu Putih', 'satuan' => 'Kaleng'],
            ['nama_barang' => 'Teh Tubruk', 'satuan' => 'Pack'],
            ['nama_barang' => 'Tepung Terigu', 'satuan' => 'Kg'],
            ['nama_barang' => 'Terasi', 'satuan' => 'Renteng'],
            ['nama_barang' => 'Tolak Angin', 'satuan' => 'Kotak'],
            ['nama_barang' => 'Ultra Flu', 'satuan' => 'Pleg'],
            ['nama_barang' => 'Pembersih lantai', 'satuan' => '-'],
            ['nama_barang' => 'Pembersih kamar mandi', 'satuan' => '-'],
            ['nama_barang' => 'Filter Oli PS C - 1004', 'satuan' => '-'],
            ['nama_barang' => 'Filter Solar PS FC -1003', 'satuan' => '-'],
            ['nama_barang' => 'Filter Solar Nissan F - 1802', 'satuan' => '-'],
            ['nama_barang' => 'Filter Solar Nissan FC - 1805', 'satuan' => '-'],
            ['nama_barang' => 'Filter Oli Nissan 018051', 'satuan' => '-'],
            ['nama_barang' => 'Filter Oli Nissan 01808', 'satuan' => '-'],
            ['nama_barang' => 'Busi Alkon BP5ES', 'satuan' => '-'],
            ['nama_barang' => 'Busi Sampan B8HS-10', 'satuan' => '-'],
            ['nama_barang' => 'Sil Sampan', 'satuan' => '-'],
            ['nama_barang' => 'Oli Sampan 4L', 'satuan' => '-'],
            ['nama_barang' => 'Oli Gardan Sampan', 'satuan' => '-'],
            ['nama_barang' => 'Baterai Besar', 'satuan' => '-'],
            ['nama_barang' => 'Baterai Kecil', 'satuan' => '-'],
            ['nama_barang' => 'Lampu kelop', 'satuan' => '-'],
            ['nama_barang' => 'Tali 6 mm', 'satuan' => '-'],
            ['nama_barang' => 'Tali 8 mm', 'satuan' => '-'],
            ['nama_barang' => 'Benang D24', 'satuan' => '-'],
            ['nama_barang' => 'Benang D18', 'satuan' => '-'],
            ['nama_barang' => 'Benang D15', 'satuan' => '-'],
            ['nama_barang' => 'Oli S40', 'satuan' => '-'],
            ['nama_barang' => 'Oli S10', 'satuan' => '-'],
            ['nama_barang' => 'Tali Rumpon', 'satuan' => '-'],
            ['nama_barang' => 'Pelampung Besar', 'satuan' => '-'],
            ['nama_barang' => 'Korek tembak', 'satuan' => '-'],
            ['nama_barang' => 'Propeler sampan', 'satuan' => '-'],
            ['nama_barang' => 'Handle sampan', 'satuan' => '-'],
            ['nama_barang' => 'Lampu sampan', 'satuan' => '-'],
            ['nama_barang' => 'Kipas Lampu LED', 'satuan' => '-'],
            ['nama_barang' => 'Dinamo stater RF8', 'satuan' => '-'],
            ['nama_barang' => 'Selang nozzel RF8', 'satuan' => '-'],
            ['nama_barang' => 'Kipas Kiyongan', 'satuan' => '-'],
            ['nama_barang' => 'Sil kiyongan NOK', 'satuan' => '-'],
            ['nama_barang' => 'Laher Kiyongan 30205 ASB', 'satuan' => '-'],
            ['nama_barang' => 'Sil 22 x 38', 'satuan' => '-'],
            ['nama_barang' => 'AS kiyongan', 'satuan' => '-'],
            ['nama_barang' => 'Kiyongan JRM 1 1/2 kiri', 'satuan' => '-'],
            ['nama_barang' => 'Stempet Formula', 'satuan' => '-'],
            ['nama_barang' => 'Air aki 5 liter', 'satuan' => '-'],
            ['nama_barang' => 'Cas Aki Maestro 30 A', 'satuan' => '-'],
            ['nama_barang' => 'Coban no 4', 'satuan' => '-'],
            ['nama_barang' => 'Coban no 5', 'satuan' => '-'],
            ['nama_barang' => 'Coban no 2', 'satuan' => '-'],
            ['nama_barang' => 'Karpet durian 1cm', 'satuan' => '-'],
            ['nama_barang' => 'Vanbelt B59', 'satuan' => '-'],
            ['nama_barang' => 'Vanbelt B44', 'satuan' => '-'],
            ['nama_barang' => 'Vanbelt B48', 'satuan' => '-'],
            ['nama_barang' => 'Vanbelt B34', 'satuan' => '-'],
            ['nama_barang' => 'Vanbelt B40', 'satuan' => '-'],
            ['nama_barang' => 'Vanbelt B61', 'satuan' => '-'],
            ['nama_barang' => 'Cat avian putih', 'satuan' => '-'],
            ['nama_barang' => 'Epoxy cat', 'satuan' => '-'],
            ['nama_barang' => 'Solasi TSB', 'satuan' => '-'],
            ['nama_barang' => 'Cat emco seri 99', 'satuan' => '-'],
            ['nama_barang' => 'Cat emco seri 102', 'satuan' => '-'],
            ['nama_barang' => 'Cat emco seri 78', 'satuan' => '-'],
            ['nama_barang' => 'Cat emco 118', 'satuan' => '-'],
            ['nama_barang' => 'Kawat las RD', 'satuan' => '-'],
            ['nama_barang' => 'Dempul kapal', 'satuan' => '-'],
            ['nama_barang' => 'Kacamata selam', 'satuan' => '-'],
            ['nama_barang' => 'Waring', 'satuan' => '-'],
            ['nama_barang' => 'SOLAR', 'satuan' => '-'],
            ['nama_barang' => 'BENSIN', 'satuan' => '-'],
            ['nama_barang' => 'ES', 'satuan' => '-'],
            ['nama_barang' => 'BLARAK', 'satuan' => '-'],
        ];

        foreach ($rows as $row) {
            DB::table('master_perbekalan')->updateOrInsert(
                ['nama_barang' => $row['nama_barang']],
                [
                    'satuan' => $row['satuan'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }
}
